apiVersion: v1
kind: ConfigMap
metadata:
  name: cltl-config
data:
  DEFAULT: |
      name: cltl-eliza
  cltl.event.kombu: |
      server: amqp://cltl:cltl@cltli-eliza-rabbitmq:5672
      exchange: cltl.combot
      type: direct
      compression: bzip2
  cltl.chat-ui.events: |
      local: False
      topic_utterance: {{ .Values.topics.utterance }}
      topic_response: {{ .Values.topics.response }}
